# This file will be populated by GitHub Actions during build
# It will not contain actual values in the repository
api_key: 'FIREBASE_API_KEY_PLACEHOLDER'
auth_domain: 'FIREBASE_AUTH_DOMAIN_PLACEHOLDER'
database_url: 'FIREBASE_DATABASE_URL_PLACEHOLDER'
project_id: 'FIREBASE_PROJECT_ID_PLACEHOLDER'
storage_bucket: 'FIREBASE_STORAGE_BUCKET_PLACEHOLDER'
messaging_sender_id: 'FIREBASE_MESSAGING_SENDER_ID_PLACEHOLDER'
app_id: 'FIREBASE_APP_ID_PLACEHOLDER'
measurement_id: 'FIREBASE_MEASUREMENT_ID_PLACEHOLDER'