name: Build and Deploy to Firebase
on:
  push:
    branches:
      - main
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt1-dev imagemagick libmagickwand-dev
          identify -version # Verify ImageMagick installation
          pkg-config --list-all | grep -i magick # Check if pkg-config can find ImageMagick
          
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:$PKG_CONFIG_PATH
          bundle install --jobs 4 --retry 3
          npm ci

      - name: Update Firebase Config
        run: |
          # Create a temporary file with actual values
          cat > _data/firebase_config.yml << EOL
          api_key: '${{ secrets.FIREBASE_API_KEY }}'
          auth_domain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'
          database_url: '${{ secrets.FIREBASE_DATABASE_URL }}'
          project_id: '${{ secrets.FIREBASE_PROJECT_ID }}'
          storage_bucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'
          messaging_sender_id: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'
          app_id: '${{ secrets.FIREBASE_APP_ID }}'
          measurement_id: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'
          EOL

      - name: Build site
        run: |
          npm run build:production
        env:
          JEKYLL_ENV: production
          
      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools
          firebase --version
          
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'